on:
  release:
    types: [released]

name: Build

jobs:
  build:
  strategy:
      matrix:
        platform: [linux-x86_64, macos-x86_64]
        include:
          - platform: linux-x86_64
            ci_image: ubuntu-latest
          - platform: macos-x86_64
            ci_image: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Download Redis
        run: |
          wget https://github.com/redis/redis/archive/${{ github.event.release.name }}.tar.gz
          tar -xzf ${{ github.event.release.name }}.tar.gz
      - name: Build
        working-directory: ./redis-${{ github.event.release.name }}
        run: make CFLAGS="-static" LDFLAGS="-static" -j
      - name: Pack
        working-directory: ./redis-${{ github.event.release.name }}
        run: |
          cp src/redis-server ./
          tar -zcvf redis-server-${{ matrix.platform }}.tar.gz redis-server
          cp redis-server-${{ matrix.platform }}.tar.gz ../
      - name: Upload Release Asset
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs').promises;
            github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ github.event.release.id }},
              name: 'redis-server-${{ matrix.platform }}.tar.gz',
              data: await fs.readFile('redis-server-${{ matrix.platform }}.tar.gz')
            });
