on:
  release:
    types: [released]

name: Build

env:
  REDIS_VERSION: 7.0.8

jobs:
  build:
    strategy:
      matrix:
        platform: [linux-x86_64, macos-x86_64]
        include:
          - platform: linux-x86_64
            ci_image: ubuntu-22.04
            make_command: make CFLAGS="-static" LDFLAGS="-static" -j
          - platform: macos-x86_64
            ci_image: macos-12
            make_command: make CFLAGS="-static" -j
    runs-on: ${{ matrix.ci_image }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Download Redis
        run: |
          wget https://github.com/redis/redis/archive/${{ env.REDIS_VERSION }}.tar.gz
          tar -xzf ${{ env.REDIS_VERSION }}.tar.gz
      - name: Build
        working-directory: ./redis-${{ env.REDIS_VERSION }}
        run: ${{ matrix.make_command }}
      - name: Pack
        working-directory: ./redis-${{ env.REDIS_VERSION }}
        run: |
          cp src/redis-server ./
          tar -zcvf redis-server-${{ matrix.platform }}.tar.gz redis-server
          cp redis-server-${{ matrix.platform }}.tar.gz ../
      - name: Upload Release Asset
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs').promises;
            github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ github.event.release.id }},
              name: 'redis-server-${{ matrix.platform }}.tar.gz',
              data: await fs.readFile('redis-server-${{ matrix.platform }}.tar.gz')
            });
